In [1]:
%load_ext autoreload
%autoreload 2

In [2]:

import altair as alt

from tools import get_all_files, get_GHG_file_df
from tools.Plot_GHG import get_GHG_plots

In [3]:
# Get the root directory of the data
data_root = '../2023_11_03__17_49_42_hard_mincost_RF30_P1e4_Won_Gon'

# Get all output files
files = get_all_files(data_root)

In [4]:
# Select files based on criteria
files_selc = files.query('year <= 2050')
print(files_selc['catetory'].unique(),'\n')

files_selc

['GHG' 'dvar' 'ammap' 'lmmap' 'lumap_separate' 'lumap' 'water'
 'cross_table' 'quantity']

,year,catetory,base_name,base_ext,path
0,2010,GHG,GHG_emissions,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
1,2010,GHG,GHG_emissions_separate_agricultural_landuse,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
2,2010,GHG,GHG_emissions_separate_agricultural_management,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
3,2010,GHG,GHG_emissions_separate_no_ag_reduction,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
4,2010,GHG,GHG_emissions_separate_transition_penalty,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
...,...,...,...,...,...
2482,2050,cross_table,switches-irrstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
2483,2050,cross_table,switches-lmmap,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
2484,2050,cross_table,switches-lumap,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
2485,2050,cross_table,switches-precision-agriculture-amstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
2486,2050,water,water_demand_vs_use,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...

### Get the total area(km2) change

In [9]:
Area_df = files_selc.query('catetory == "cross_table"').reset_index(drop=True)
Area_df

,year,catetory,base_name,base_ext,path
0,2011,cross_table,crosstab-asparagopsis-taxiformis-amstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
1,2011,cross_table,crosstab-ecological-grazing-amstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
2,2011,cross_table,crosstab-irrstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
3,2011,cross_table,crosstab-lmmap,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
4,2011,cross_table,crosstab-lumap,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
...,...,...,...,...,...
475,2050,cross_table,switches-ecological-grazing-amstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
476,2050,cross_table,switches-irrstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
477,2050,cross_table,switches-lmmap,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
478,2050,cross_table,switches-lumap,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...
479,2050,cross_table,switches-precision-agriculture-amstat,.csv,../2023_11_03__17_49_42_hard_mincost_RF30_P1e4...